addons:
  firefox: "49.0"

language: scala

jdk: oraclejdk8

scala:
   - 2.11.8

before_script:
    # start xvfb
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start