sudo: required

addons:
  firefox: "55.0"

language: scala

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
  - ./project/travis/install-geckodriver.sh

jdk: oraclejdk8

scala:
   - 2.11.8